import type { Metadata } from "next";
import localFont from "next/font/local";
import { Space_Mono } from 'next/font/google'; // Añade esta importación
import "./global.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Añade Space Mono
const spaceMono = Space_Mono({
  weight: ['400', '700'], // Puedes ajustar los pesos que necesites
  subsets: ['latin'],
  variable: '--font-space-mono', // Define la variable CSS
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${spaceMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}